# Generated by Django 4.2.11 on 2024-03-23 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.country'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='acountUser_recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient', to='main.acountuser'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='customer_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to='main.customerinfo'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='acountUser_giver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giver', to='main.acountuser'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='customer_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='main.customerinfo'),
        ),
    ]
